### ISSUE TITLE
chat

### ISSUE THREAD

**Issue by ls-2018** [googs1025/crictl-plugin-develop#1]
![image](https://user-images.githubusercontent.com/38821215/217562413-342ecdbb-11da-4384-af68-899badcb736b.png)
兄弟刚看见，居然有人给我star了，看你挺厉害的。特来索要一下微信☺    acejilam@gmail.com

**Comment by googs1025** [comment]
您好，哈哈哈，我刚学习不久，还有很多东西在摸索。
你可以直接加我 googs1025 一起交流学习！
